# 1. We don't need to use `sudo`, and can instead use containers for faster builds
sudo: false
# 2. This is a Python project
language: python
# 3. These are the various versions of python we want to test against
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
# command to run tests
script:
  - python test.py
